name: MYfedtorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2022.5.18.1=h033912b_0
  - certifi=2022.5.18.1=py39h6e9494a_0
  - intel-openmp=2022.0.0=hecd8cb5_3615
  - joblib=1.1.0=pyhd8ed1ab_0
  - libblas=3.9.0=14_osx64_mkl
  - libcblas=3.9.0=14_osx64_mkl
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - liblapack=3.9.0=14_osx64_mkl
  - libuv=1.40.0=haf1e3a3_0
  - llvm-openmp=14.0.4=ha654fa7_0
  - mkl=2022.0.0=hecd8cb5_105
  - ncurses=6.3=hca72f7f_2
  - openssl=1.1.1o=hfe4f2af_0
  - pandas=1.4.1=py39h4d6be9b_0
  - pip=21.2.4=py39hecd8cb5_0
  - python=3.9.7=h88f2d9e_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.2=py3.9_0
  - pytz=2022.1=pyhd8ed1ab_0
  - readline=8.1.2=hca72f7f_1
  - scikit-learn=1.0.2=py39hd4eea88_0
  - scipy=1.8.0=py39h056f1c0_1
  - setuptools=58.0.4=py39hecd8cb5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.2=h707629a_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.11=h7bc2e8c_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h4dc903c_4
  - pip:
    - absl-py==1.0.0
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - cycler==0.11.0
    - fonttools==4.29.1
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - idna==3.3
    - importlib-metadata==4.11.0
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - numpy==1.22.2
    - oauthlib==3.2.0
    - packaging==21.3
    - pillow==9.0.1
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.7
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - torchsummary==1.5.1
    - torchvision==0.11.3
    - urllib3==1.26.8
    - werkzeug==2.0.3
    - zipp==3.7.0
prefix: /opt/miniconda3/envs/MYfedtorch
